### ISSUE TITLE
Update `pull` to treat Data Builder as other images

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/opensafely-cli#158]
Modify `opensafely  pull` to automatically pull Data Builder images.

The image is currently explicitly excluded:

https://github.com/opensafely-core/opensafely-cli/blob/b3b66217652673ce1800b8971a4859e7343f76a6/opensafely/pull.py#L68-L70

A slight complexity is that we want to use `v0` for all Data Builder images rather than `latest`, so we need a bit of logic to vary the tag in this line:

https://github.com/opensafely-core/opensafely-cli/blob/b3b66217652673ce1800b8971a4859e7343f76a6/opensafely/pull.py#L75

Note that this is a somewhat short-term solution. We'd really like to move to specifying versions for all images, allow those versions to vary between studies and also simplify the surface and implementation of `opensafely pull`. However that's considered too much to bite off as part of the Data Builder work. So this issue is the minimum we can do to 1) allow researchers to easily use Data Builder and 2) set off on the right foot by at least requiring the version of Data Builder to be specified explicitly (everyone will have to specify `databuilder:v0` in their `pipeline.yaml`). This supersedes the discussion in the comments below.

**Comment by benbc** [comment]
Do we know if people actually do `opensafely pull databuilder` rather than just `opensafely pull`? I didn't even know it was a thing; the CLI itself encourages you to do `opensafely pull`.

**Comment by evansd** [comment]
Well they have to run `opensafely pull <image>` at some point otherwise they'll never have any images to update. Although looking at the code, maybe they use the `--project` option which pulls all images referenced in `project.yaml`.

**Comment by benbc** [comment]
The getting started guide has `opensafely pull cohortextractor`, so I expect they do that. I probably did that once a year and a half ago and then forgot all about it.

**Comment by benbc** [comment]
> What should opensafely pull databuilder do?

@evansd Maybe read the tag out of `pipeline.yaml`? (And error if there isn't one there.)

**Comment by benbc** [comment]
There also seems to be `opensafely pull all`, to avoid people having to know what images they want.

**Comment by bloodearnest** [comment]
So, if the image is versioned with with a non-`latest` tag, I think `opensafely` pull is not needed.

I think that job-runner should always pull such images, by adding `--pull` to the `docker run` command.

I think `opensafely pull` should only apply to images using ":latest" tag.

That way, I think this change and its complexities are not needed.

**Comment by bloodearnest** [comment]
sorry, totally didn't mean to close that

**Comment by benbc** [comment]
@bloodearnest Could you explain why we always want to pull images with explicit versions?

**Comment by evansd** [comment]
I agree that in production we should be automatically pulling in the latest image (which is effectively what happens in the `research-action` tests anyway).

I do think the local requirements are a bit different. Not just because pulling down gigabytes of data without asking the user is a bit rude for the ghickman's of this world; but also because switching versions of software out from under the user doesn't feel very well-behaved to me.

Checking for updates and prompting the user to install them does feel like the right thing here, although it involves a bit of complexity.

Things would be simpler if we always required a version argument e.g

    opensafely pull databuilder:v1

Thought that feels a bit pointless until we actual have version tags for all the images.
